# Generated by Django 4.1.6 on 2023-02-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('auto', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('año', models.CharField(max_length=200)),
                ('seguro', models.CharField(max_length=200)),
                ('placas', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200)),
                ('imagenes', models.CharField(max_length=200)),
            ],
        ),
    ]
