# Generated by Django 4.1.6 on 2023-02-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpertoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla_test',
            name='nombre',
        ),
    ]
