# Generated by Django 4.1.6 on 2023-02-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpertoapp', '0002_remove_tabla_test_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
                ('descripcion', models.TextField(null=True)),
                ('auto', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('año', models.CharField(max_length=200)),
                ('seguro', models.CharField(max_length=200)),
                ('placas', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tabla_test',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='tabla_test',
            name='año',
        ),
        migrations.RemoveField(
            model_name='tabla_test',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='tabla_test',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='tabla_test',
            name='placas',
        ),
        migrations.RemoveField(
            model_name='tabla_test',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='tabla_test',
            name='seguro',
        ),
    ]
