# Generated by Django 4.1.6 on 2023-02-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpertoapp', '0003_auto_remove_tabla_test_auto_remove_tabla_test_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
