# Generated by Django 4.1.6 on 2023-02-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpertoapp', '0005_alter_auto_descripcion_alter_auto_imagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla_test',
        ),
    ]
