# Generated by Django 4.1.6 on 2023-02-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpertoapp', '0006_delete_tabla_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auto',
            new_name='autos',
        ),
    ]
