# Generated by Django 4.1.6 on 2023-02-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpertoapp', '0008_rename_autos_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='auto',
            new_name='datos_auto',
        ),
    ]
