# Generated by Django 4.1.6 on 2023-02-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoexpertoapp', '0010_remove_auto_imagen_remove_auto_titulo_auto_imagen_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosdelauto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='auto',
        ),
    ]
